# Generated by Django 4.1.7 on 2023-03-19 10:51

import django.core.validators
from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_pic',
            field=models.ImageField(blank=True, null=True, upload_to=teacher.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
        ),
    ]
