# Generated by Django 4.1.7 on 2023-03-25 12:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import students.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('class_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_no', models.PositiveIntegerField(default=0, max_length=3)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Invalid mobile no')])),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('dob', models.DateField(default='2023-03-17')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('blood_group', models.CharField(max_length=6)),
                ('address', models.TextField(validators=[django.core.validators.MaxLengthValidator(50)])),
                ('state', models.CharField(choices=[('bihar', 'Bihar'), ('up', 'UP'), ('jh', 'Jharkhand')], max_length=10)),
                ('dist', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Invalid postal code')])),
                ('parent_mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Invalid mobile no')])),
                ('parent_email', models.EmailField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('father_occupation', models.CharField(max_length=30)),
                ('mother_occupation', models.CharField(max_length=30)),
                ('parent_doc_type', models.CharField(choices=[('pan', 'PAN Card'), ('aadhar', 'Aadhar Card'), ('Passport', 'Passport'), ('dl', 'Driving License'), ('voter_id', 'Voter ID')], max_length=10)),
                ('parent_doc_no', models.CharField(max_length=10)),
                ('student_doc_type', models.CharField(choices=[('pan', 'PAN Card'), ('aadhar', 'Aadhar Card'), ('Passport', 'Passport'), ('dl', 'Driving License'), ('voter_id', 'Voter ID')], max_length=15)),
                ('student_doc_no', models.CharField(max_length=15)),
                ('student_pic', models.ImageField(blank=True, null=True, upload_to=students.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])])),
                ('parent_pic', models.ImageField(blank=True, null=True, upload_to=students.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])])),
                ('student_doc_pdf', models.FileField(blank=True, null=True, upload_to=students.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('parent_doc_pdf', models.FileField(blank=True, null=True, upload_to=students.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('classes', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='students.classes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
