# Generated by Django 4.1.7 on 2023-03-17 10:36

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_doc_pic',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.Student.image_file_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_pic',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.Student.image_file_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='previous_class_doc_pic',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.Student.image_file_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_doc_pic',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_pic',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.get_file_path),
        ),
    ]
