# Generated by Django 4.1.7 on 2023-03-17 20:14

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_first_name_alter_student_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_doc_pic',
            new_name='parent_doc_back_pic',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_doc_pic',
            new_name='student_doc_back_pic',
        ),
        migrations.AddField(
            model_name='student',
            name='parent_doc_front_pic',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.Student.image_file_path),
        ),
        migrations.AddField(
            model_name='student',
            name='student_doc_front_pic',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.get_file_path),
        ),
    ]
