# Generated by Django 4.1.7 on 2023-03-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_rename_parent_doc_pic_student_parent_doc_back_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_doc_back_pic',
            new_name='parent_doc_pic',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_doc_back_pic',
            new_name='student_doc_pic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_doc_front_pic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_doc_front_pic',
        ),
    ]
