# Generated by Django 4.1.7 on 2023-03-17 22:33

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_parent_doc_back_pic_student_parent_doc_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_pic',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.get_file_path),
        ),
    ]
