# Generated by Django 4.1.7 on 2023-03-17 22:55

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_parent_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_doc_pic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='previous_class_doc_pic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_doc_pic',
        ),
        migrations.AddField(
            model_name='student',
            name='parent_doc_pdf',
            field=models.FileField(blank=True, null=True, upload_to=students.models.get_file_path),
        ),
        migrations.AddField(
            model_name='student',
            name='student_doc_pdf',
            field=models.FileField(blank=True, null=True, upload_to=students.models.get_file_path),
        ),
    ]
