# Generated by Django 4.1.7 on 2023-03-18 12:42

import django.core.validators
from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_student_parent_doc_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_doc_pdf',
            field=models.FileField(blank=True, null=True, upload_to=students.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_pic',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_doc_pdf',
            field=models.FileField(blank=True, null=True, upload_to=students.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_pic',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jgg'])]),
        ),
    ]
