# Generated by Django 4.1.7 on 2023-03-19 10:51

import django.core.validators
from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_parent_doc_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_pic',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
        ),
    ]
