# Generated by Django 4.1.7 on 2023-03-24 20:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignRollNoModel',
            fields=[
                ('assign_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_no', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='students.classes')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='students.student')),
            ],
        ),
    ]
