# Generated by Django 4.1.7 on 2023-03-30 08:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignRollNoModel',
            fields=[
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('assign_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_id', models.UUIDField()),
                ('student_id', models.UUIDField()),
                ('full_name', models.CharField(max_length=40)),
                ('class_name', models.CharField(max_length=10)),
                ('roll_no', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
