# Generated by Django 4.1.7 on 2023-03-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignrollnomodel',
            name='roll_no',
            field=models.IntegerField(unique=True),
        ),
    ]
