# Generated by Django 4.1.7 on 2023-04-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_roll_no'),
        ('appadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignrollnomodel',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='assignrollnomodel',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='assignrollnomodel',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='assignrollnomodel',
            name='student_id',
        ),
        migrations.AddField(
            model_name='assignrollnomodel',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to='students.student'),
        ),
        migrations.AlterModelTable(
            name='assignrollnomodel',
            table='rollno_assign',
        ),
    ]
