# Generated by Django 4.1.7 on 2023-03-30 08:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendanceModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(max_length=40)),
                ('teacher_name', models.CharField(max_length=40)),
                ('class_id', models.CharField(max_length=40)),
                ('class_name', models.CharField(max_length=40)),
                ('student_id', models.CharField(max_length=40)),
                ('student_name', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('holiday', 'Holiday'), ('holiday', 'Holiday'), ('leave', 'Leave'), ('half_day_leave', 'Half-Day Leave')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
