# Generated by Django 4.1.7 on 2023-04-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendancemodel',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('holiday', 'Holiday'), ('holiday', 'Holiday'), ('leave', 'Leave'), ('vacation', 'Vacation'), ('half_day_leave', 'Half-Day Leave')], max_length=20),
        ),
    ]
